- name: Creating catalogue service
  hosts: all
  become: yes
  tasks:
    - name: DOWNLOADING NODEJS REPO
      ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x

    - name: Installing Nodejs Service
      ansible.builtin.yum:
        name: nodejs
        state: latest

    - name: Adding user
      ansible.builtin.user:
        name: roboshop

    - name: create a directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Downloading new app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Installing npm
      ansible.builtin.shell:npm install
      args:
        chdir: /app


    - name: Configuring catalogue service
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: DOWNLOADING MONGODB repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: Installing mongod
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: latest

    - name: Loading Mongo Schema
      ansible.builtin.shell: mongo --host mongodb-dev.sindhu.cloud

    - name: Enabling and starting the catalogue server
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes






echo -e "$color CREATING CATALOGUE SERVICE$nocolor"
cp /root/repo-shell/catalogue.service /etc/systemd/system/catalogue.service
echo -e "$color DOWNLOADING AND INSTALLING THE MONGODB SCHEMA$nocolor"
cp /root/repo-shell/mongodb.repo /etc/yum.repos.d/mongodb.repo
yum install mongodb-org-shell -y &>>${logfile}
mongo --host mongodb-dev.sindhu.cloud <${app_path}/schema/catalogue.js &>>${logfile}
echo -e "$color ENABLING AND STARTING THE CATALOGUE SERVICE$nocolor"
systemctl daemon-reload
systemctl enable catalogue &>>${logfile}
systemctl restart catalogue