- name: creating rabbitmq server
  hosts: all
  become: yes
  tasks:
    - name: Installing rabbitmq repo
      ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

    - name: Installing rabbitmq repo
      ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

    - name: Installing rabbitmq-server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: latest

    - name: Enabling and restarting rabbitmq-server
      ansible.builtin.systemd:
        state: restarted
        name: rabbitmq-server
        enabled: true

    - name: Adding user
      ansible.builtin.user:
        name: roboshop roboshop123

    - name: setting permissions
      ansible.builtin.user:
        name: set_permissions -p / roboshop ".*" ".*" ".*"



